---
- name: "Become section"
  block:
    - name: "Install requirements"
      package:
        name: "{{ package }}"
        state: "present"
      loop: "{{ requirements }}"
      loop_control:
        loop_var: package

    - name: "Extract MDEX installer"
      unarchive:
        src: "{{ mdex_artifact }}"
        dest: "{{ download_path }}"
        list_files: True
      register: mdex_installer

    - name: "Create endeca group"
      become: True
      group:
        name: "{{ endeca_group }}"
        state: "present"

    - name: "Create endeca user"
      user:
        name: "{{ endeca_user }}"
        group: "{{ endeca_group }}"
        state: "present"
        home: "/home/{{ endeca_user }}"
        createhome: True
        append: True

    - name: "Create endeca root folder with {{ endeca_user }} as owner"
      file:
        owner: "{{ endeca_user }}"
        group: "{{ endeca_group }}"
        path: "{{ base_root }}/endeca"
        state: "directory"

    - name: "Ensure {{ mdex_installer.files[0] }} is executable"
      file:
      args:
        path: "{{ download_path }}/{{ mdex_installer.files[0] }}"
        owner: "{{ endeca_user }}"
        group: "{{ endeca_group }}"
        mode: "0755"

  become: True

- name: "Set mdex_installer_bin"
  set_fact:
    mdex_installer_bin: "{{ download_path }}/{{ mdex_installer.files[0] }}"

# MDEX versions lower 6.5.2
- name: "Run installer"
  become_user: "{{ endeca_user }}"
  command: "{{ mdex_installer_bin }} --silent --target {{ base_root }}"
  args:
    creates: "{{ mdex_path }}"
  become: True
  when: mdex_version is match("^[1-6].[0-4].[0-9]") or mdex_version is match("^6.5.[0-1]")

- name: "Install MDEX{{ mdex_version }}"
  block:
    - name: "Create silent install file for MDEX{{ mdex_version }}"
      template:
        src: "mdex_installer.properties.j2"
        dest: "{{ download_path }}/mdex_installer_{{ mdex_version }}.properties"

    - name: "Run installer"
      become_user: "{{ endeca_user }}"
      command: "{{ mdex_installer_bin }} -i silent -f mdex_installer_{{ mdex_version }}.properties"
      args:
        creates: "{{ mdex_path }}"
      become: True

  when: not (mdex_version is match("^[1-6].[0-4].[0-9]") or mdex_version is match("^6.5.[0-1]"))

- name: "Become section"
  block:
    - name: "Enable connections to {{ mdex_port }} port"
      seport:
        ports: "{{ mdex_port }}"
        proto: "tcp"
        setype: "http_port_t"
        state: "present"
      when: ansible_selinux.status == "enabled"

    - name: "Put mdex profile"
      copy:
        src: "{{ mdex_path }}/mdex_setup_sh.ini"
        dest: "/etc/profile.d/mdex.sh"
        owner: "root"
        group: "root"
        mode: "0555"
        remote_src: True

  become: True
